In [ ]:
import pm4py
import pandas as pd

In [33]:
XES_PATH = "../data/resource/resource_001.xes"
CSV_PATH = "../data/resource/template.csv"

In [44]:
log = pm4py.read_xes(XES_PATH)
print(log["start_timestamp"][3160:3165])
log.head(5)

parsing log, completed traces ::   0%|          | 0/1000 [00:00<?, ?it/s]

parsing log, completed traces :: 100%|██████████| 1000/1000 [00:00<00:00, 21343.32it/s]

3160   2020-02-10 06:00:37.060846+00:00
3161   2020-02-10 06:16:14.972048+00:00
3162   2020-02-10 06:10:54.092327+00:00
3163   2020-02-10 06:26:26.962050+00:00
3164   2020-02-10 06:33:36.007116+00:00
Name: start_timestamp, dtype: datetime64[us, UTC]

,event:id,concept:name,start_timestamp,time:timestamp,event:duration_min,org:resource,org:role,case:concept:name,case:case_type,case:amount,case:region
0,evt_00000001,c,2020-01-01 00:58:50.608867+00:00,2020-01-01 01:11:53.127724+00:00,13.041981,res_016,role_01,case_000001,type_03,1266.32,DE-HE
1,evt_00000002,a,2020-01-01 01:13:33.039310+00:00,2020-01-01 01:29:02.844833+00:00,15.496759,res_015,role_05,case_000001,type_03,1266.32,DE-HE
2,evt_00000003,d,2020-01-01 01:30:24.898397+00:00,2020-01-01 01:42:17.727007+00:00,11.880477,res_004,role_04,case_000001,type_03,1266.32,DE-HE
3,evt_00000004,c,2020-01-01 01:18:14.785646+00:00,2020-01-01 01:27:04.499935+00:00,8.828571,res_016,role_01,case_000002,type_03,1352.79,DE-HE
4,evt_00000005,a,2020-01-01 01:29:14.759986+00:00,2020-01-01 01:31:27.234802+00:00,2.207914,res_013,role_03,case_000002,type_03,1352.79,DE-HE

In [14]:
variants = pm4py.get_variants(log)
print(variants)

{('c', 'a', 'd'): 658, ('e', 'f', 'b', 'a', 'd'): 342}

In [39]:
df = pd.read_csv(CSV_PATH)
df = pm4py.format_dataframe(
    df,
    case_id="case:concept:name",
    activity_key="concept:name",
    timestamp_key="time:timestamp"
)
df.head(5)

,event:id,concept:name,start_timestamp,time:timestamp,event:duration_min,org:resource,org:role,case:concept:name,case:case_type,case:amount,case:region,@@index,@@case_index
0,evt_00000001,c,2020-01-01 00:58:50+00:00,2020-01-01 01:11:53+00:00,13.041981,res_016,role_01,case_000001,type_03,1266.32,DE-HE,0,0
1,evt_00000002,a,2020-01-01 01:13:33+00:00,2020-01-01 01:29:02+00:00,15.496759,res_015,role_05,case_000001,type_03,1266.32,DE-HE,1,0
2,evt_00000003,d,2020-01-01 01:30:24+00:00,2020-01-01 01:42:17+00:00,11.880477,res_004,role_04,case_000001,type_03,1266.32,DE-HE,2,0
3,evt_00000004,c,2020-01-01 01:18:14+00:00,2020-01-01 01:27:04+00:00,8.828571,res_016,role_01,case_000002,type_03,1352.79,DE-HE,3,1
4,evt_00000005,a,2020-01-01 01:29:14+00:00,2020-01-01 01:31:27+00:00,2.207914,res_013,role_03,case_000002,type_03,1352.79,DE-HE,4,1

In [35]:
variants = pm4py.get_variants(df)
print(variants)

{('c', 'a', 'd'): 658, ('e', 'f', 'b', 'a', 'd'): 342}