In [2]:
import pm4py
import warnings
import pandas as pd

In [4]:
warnings.filterwarnings("ignore")
log = pm4py.read_xes("../data/bpi-log.xes")
log.head()

parsing log, completed traces :: 100%|███████████████████████████████████████████████████████████████████████████████████| 13087/13087 [00:00<00:00, 24140.09it/s]

,case:REG_DATE,org:resource,concept:name,lifecycle:transition,case:AMOUNT_REQ,time:timestamp,case:concept:name
0,2011-10-01 02:38:00+00:00,112,submitted,COMPLETE,20000,2011-10-01 02:38:00+00:00,173688
1,2011-10-01 02:38:00+00:00,112,pre-accepted,COMPLETE,20000,2011-10-01 02:39:00+00:00,173688
2,2011-10-01 02:38:00+00:00,10862,accepted,COMPLETE,20000,2011-10-01 13:42:00+00:00,173688
3,2011-10-01 02:38:00+00:00,10862,finalized,COMPLETE,20000,2011-10-01 13:45:00+00:00,173688
4,2011-10-01 02:38:00+00:00,10629,registered,COMPLETE,20000,2011-10-13 12:37:00+00:00,173688

In [7]:
warnings.filterwarnings("ignore")
log = pm4py.read_xes("../data/inter.xes")
log.head()

parsing log, completed traces :: 100%|█████████████████████████████████████████████████████████████████████████████████████| 7304/7304 [00:00<00:00, 18414.72it/s]

,event:id,concept:name,start_timestamp,time:timestamp,event:duration_min,org:resource,case:concept:name,case:amount,case:region
0,evt_00000001,b,2020-01-01 00:00:00+00:00,2020-01-01 00:41:00.933432+00:00,41.015557,res_01,case_000001,710.74,region_3
1,evt_00000002,c,2020-01-01 01:06:51.766801+00:00,2020-01-01 01:32:28.979337+00:00,25.620209,res_07,case_000001,710.74,region_3
2,evt_00000003,d,2020-01-01 01:45:52.850977+00:00,2020-01-01 02:15:22.658851+00:00,29.496798,res_07,case_000001,710.74,region_3
3,evt_00000004,e,2020-01-01 02:21:52.493678+00:00,2020-01-01 02:50:04.447137+00:00,28.199224,res_03,case_000001,710.74,region_3
4,evt_00000005,f,2020-01-01 03:02:46.924285+00:00,2020-01-01 03:31:31.564553+00:00,28.744004,res_08,case_000001,710.74,region_3

In [8]:
warnings.filterwarnings("ignore")
log = pm4py.read_xes("../data/resource.xes")
log.head()

parsing log, completed traces :: 100%|█████████████████████████████████████████████████████████████████████████████████████| 4386/4386 [00:00<00:00, 19141.05it/s]

,event:id,concept:name,start_timestamp,time:timestamp,event:duration_min,org:resource,case:concept:name,case:amount,case:region
0,evt_00000001,b,2020-01-01 00:00:00+00:00,2020-01-01 00:30:21.607462+00:00,30.360124,res_01,case_000001,1012.32,region_3
1,evt_00000002,c,2020-01-01 00:32:00.617436+00:00,2020-01-01 01:01:56.277398+00:00,29.927666,res_07,case_000001,1012.32,region_3
2,evt_00000003,d,2020-01-01 01:15:52.002940+00:00,2020-01-01 01:31:01.632015+00:00,15.160485,res_07,case_000001,1012.32,region_3
3,evt_00000004,e,2020-01-01 01:57:43.968071+00:00,2020-01-01 02:47:45.234771+00:00,50.021112,res_03,case_000001,1012.32,region_3
4,evt_00000005,f,2020-01-01 03:02:37.524805+00:00,2020-01-01 03:35:11.198144+00:00,32.561222,res_08,case_000001,1012.32,region_3

In [5]:
traces = (
    log.sort_values("time:timestamp")
      .groupby("case:concept:name")["concept:name"]
      .apply(list)
      .tolist()
)

In [5]:
len(traces)

2249

In [6]:
trace_lengths = [len(trace) for trace in traces]
#trace_lengths

In [7]:
import statistics

mean = statistics.mean(trace_lengths)
stdev = statistics.stdev(trace_lengths)      # sample (n-1)
variance = statistics.variance(trace_lengths)  # sample (n-1)

print(mean)
print(stdev)
print(variance)

9.13383726100489
11.030786644507087
121.67825399663592